### ISSUE TITLE
Please Qeebta "our Students says" Saxa waliba image size ka dhiga mid sax ah

### ISSUE THREAD

**Issue by Omar-Tood** [dugsiiyeinc/Dugsiiye-clone#15]
Engs Qeebtas Kulaabta insha'allah

**Comment by abdilahimohamet** [comment]
Eng okey xalay markanu online ka saarnay buu naga khaldamy markii hore wuu noo fadhiya.

**Comment by Omar-Tood** [comment]
> Eng okey xalay markanu online ka saarnay buu naga khaldamy markii hore wuu noo fadhiya.

Alright Good. Guuleysat Dhalinyaro🚀👌

**Comment by abdilahimohamet** [comment]
adaa mudan eng thanks
